CREATE TABLE calendar.tasks
(
    id               INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    description      TEXT,
    created_at       TIMESTAMPTZ DEFAULT NOW(),
    modified_at      TIMESTAMPTZ DEFAULT NOW()
);