#!/usr/bin/bash

cmd="$1"
path="$2"

set -euo pipefail

get_token() {
  curl -X POST "http://localhost:8888/realms/homeserver/protocol/openid-connect/token" \
    -H "Content-Type: application/x-www-form-urlencoded" \
    -d "client_id=message-server" \
    -d "grant_type=password" \
    -d "username=testuser" \
    -d "password=testuser123" | jq '.access_token' | tr -d "\""
}

url_encode() {
  local input_str="$1"
  printf %s "${input_str}" | jq -sRr @uri
}

get_signal_data() {
  local token
  local path_args="${1:-}"
  token=$(get_token)
  curl -v "http://localhost:8080/signaldata${path_args}" \
    -H "Content-Type:application/json" \
    -H "Authorization: Bearer ${token}" \
    -w "\n"
}

if [[ "signal_data" == "${cmd}" ]]; then
  get_signal_data "${path}"
fi
