#!/usr/bin/bash

cmd="$1"
path="$2"

set -euo pipefail

get_token() {
  curl -X POST "http://localhost:8888/realms/homeserver/protocol/openid-connect/token" \
    -H "Content-Type: application/x-www-form-urlencoded" \
    -d "client_id=message-server" \
    -d "grant_type=password" \
    -d "username=testadmin" \
    -d "password=testadmin123" | jq '.access_token' | tr -d "\""
}

url_encode() {
  local input_str="$1"
  printf %s "${input_str}" | jq -sRr @uri
}

get_signal_data() {
  local token
  local path_args="${1:-}"
  token=$(get_token)
  curl -v "http://localhost:8080/signaldata${path_args}" \
    -H "Content-Type:application/json" \
    -H "Authorization: Bearer ${token}" \
    -w "\n"
}

assign_device() {
  local token
  local body="${1:-}"
  token=$(get_token)
  curl -v "http://localhost:8080/access/assign" \
    --json "${body}" \
    -H "Content-Type:application/json" \
    -H "Authorization: Bearer ${token}" \
    -w "\n"
}

create_task() {
  local token
  local body="${1:-}"
  token=$(get_token)
  curl -v "http://localhost:8080/tasks" \
      --json "${body}" \
      -H "Content-Type:application/json" \
      -H "Authorization: Bearer ${token}" \
      -w "\n"
}


if [[ "signal_data" == "${cmd}" ]]; then
  get_signal_data "${path}"
elif [[ "assign_device" == "${cmd}" ]]; then
  assign_device '{"deviceIdentifier": "foo", "groupName": "faa"}'
elif [[ "create_task" == "${cmd}" ]]; then
  create_task '{"description": "Do all the things."}'
fi
